name: dlinoss
params:
  num_blocks: 4
  ssm_size: 64
  hidden_dim: 128
  variant: imex1
  initialization: ring
  r_min: 0.9
  r_max: 1.0
  theta_min: 0.0
  theta_max: 3.141592653589793
  A_min: -1.0e6
  A_max: 1.0e6
  G_min: -1.0e6
  G_max: 1.0e6
  dt_std: 0.5
  dropout: 0.1
