model_name: sdlinossrec
d_model: 64
ssm_size: 256
blocks: 1
dropout: ${dataset.dropout}
variant: imex1
initialization: ring
r_min: 0.9
r_max: 1.0
theta_min: 0.0
theta_max: 0.7
A_min: -1.0e6
A_max: 1.0e6
G_min: -1.0e6
G_max: 1.0e6
dt_std: 0.5
selective_injection: true
per_step_dt: true
conv_kernel: 4
use_pffn: true
use_pos_emb: false
use_layernorm: true
